language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
    - python: "nightly"
      dist: xenial
  allow_failures:
    - python: "nightly"
install: pip install -r requirements_dev.txt
script: nosetests
